-- MySQL Script generated by MySQL Workbench
-- 07/18/14 00:14:36
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET euckr ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`cd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`cd` ;

CREATE TABLE IF NOT EXISTS `test`.`cd` (
  `CDKINDID` SMALLINT(6) NOT NULL,
  `CDVAL` VARCHAR(10) NOT NULL,
  `CDNAME` VARCHAR(50) NOT NULL,
  `CDDESC` VARCHAR(200) NOT NULL,
  `CDVALOPT1` VARCHAR(100) NULL DEFAULT NULL,
  `CDVALOPT2` VARCHAR(100) NULL DEFAULT NULL,
  `CDVALOPT3` VARCHAR(100) NULL DEFAULT NULL,
  `CDVALOPT4` VARCHAR(100) NULL DEFAULT NULL,
  `CREATOR` VARCHAR(20) NOT NULL,
  `UPDATER` VARCHAR(20) NULL DEFAULT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  `CDSTAT` CHAR(1) NOT NULL,
  PRIMARY KEY (`CDKINDID`, `CDVAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`board` ;

CREATE TABLE IF NOT EXISTS `test`.`board` (
  `BOARDID` INT(11) NOT NULL,
  `CATETORYID` VARCHAR(5) NOT NULL,
  `SUBJECT` VARCHAR(60) NOT NULL,
  `CONTENT` VARCHAR(2000) NOT NULL,
  `HITCNT` INT(11) NULL DEFAULT NULL,
  `RECOMMENDCNT` INT(11) NULL DEFAULT NULL,
  `CREATOR` VARCHAR(20) NOT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`BOARDID`),
  INDEX `fk_board_cd1_idx` (`CATETORYID` ASC),
  CONSTRAINT `fk_board_cd1`
    FOREIGN KEY (`CATETORYID`)
    REFERENCES `test`.`cd` (`CDVAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`cdkind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`cdkind` ;

CREATE TABLE IF NOT EXISTS `test`.`cdkind` (
  `CDKINDID` SMALLINT(6) NOT NULL,
  `CDKINDNAME` VARCHAR(50) NOT NULL,
  `CDKINDDESC` VARCHAR(200) NOT NULL,
  `CREATOR` VARCHAR(20) NOT NULL,
  `UPDATER` VARCHAR(20) NULL DEFAULT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  `CDKINDSTAT` CHAR(1) NOT NULL,
  PRIMARY KEY (`CDKINDID`),
  CONSTRAINT `fk_cdkind_cd1`
    FOREIGN KEY (`CDKINDID`)
    REFERENCES `test`.`cd` (`CDKINDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`comment_main`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`comment_main` ;

CREATE TABLE IF NOT EXISTS `test`.`comment_main` (
  `COMMENTID` INT(11) NOT NULL,
  `BOARDID` INT(11) NOT NULL,
  `CONTENT` VARCHAR(2000) NOT NULL,
  `CREATOR` VARCHAR(20) NOT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  `board_BOARDID` INT(11) NOT NULL,
  PRIMARY KEY (`COMMENTID`, `board_BOARDID`),
  INDEX `fk_comment_a_board_idx` (`board_BOARDID` ASC),
  CONSTRAINT `fk_comment_a_board`
    FOREIGN KEY (`board_BOARDID`)
    REFERENCES `test`.`board` (`BOARDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`comment_sub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`comment_sub` ;

CREATE TABLE IF NOT EXISTS `test`.`comment_sub` (
  `SUBCOMMENTID` INT(11) NOT NULL,
  `COMMENTID` INT(11) NOT NULL,
  `CONTENT` VARCHAR(2000) NOT NULL,
  `CREATOR` VARCHAR(20) NOT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  `comment_a_COMMENTID` INT(11) NOT NULL,
  `comment_a_board_BOARDID` INT(11) NOT NULL,
  PRIMARY KEY (`SUBCOMMENTID`, `comment_a_COMMENTID`, `comment_a_board_BOARDID`),
  INDEX `fk_comment_b_comment_a1_idx` (`comment_a_COMMENTID` ASC, `comment_a_board_BOARDID` ASC),
  CONSTRAINT `fk_comment_b_comment_a1`
    FOREIGN KEY (`comment_a_COMMENTID` , `comment_a_board_BOARDID`)
    REFERENCES `test`.`comment_main` (`COMMENTID` , `board_BOARDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`poll` ;

CREATE TABLE IF NOT EXISTS `test`.`poll` (
  `POLLID` INT(11) NOT NULL,
  `BOARDID` INT(11) NOT NULL,
  `QUESTION` VARCHAR(1000) NOT NULL,
  `OPT1` VARCHAR(200) NOT NULL,
  `OPT2` VARCHAR(200) NOT NULL,
  `OPT3` VARCHAR(200) NOT NULL,
  `OPT4` VARCHAR(200) NOT NULL,
  `OPT5` VARCHAR(200) NOT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `board_BOARDID` INT(11) NOT NULL,
  PRIMARY KEY (`POLLID`, `board_BOARDID`),
  INDEX `fk_poll_board1_idx` (`board_BOARDID` ASC),
  CONSTRAINT `fk_poll_board1`
    FOREIGN KEY (`board_BOARDID`)
    REFERENCES `test`.`board` (`BOARDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`mypoll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`mypoll` ;

CREATE TABLE IF NOT EXISTS `test`.`mypoll` (
  `POLLID` INT(11) NOT NULL,
  `USERID` VARCHAR(20) NOT NULL,
  `CHOICE` CHAR(1) NOT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `poll_POLLID` INT(11) NOT NULL,
  `poll_board_BOARDID` INT(11) NOT NULL,
  PRIMARY KEY (`POLLID`, `USERID`, `poll_POLLID`, `poll_board_BOARDID`),
  INDEX `fk_mypoll_poll1_idx` (`poll_POLLID` ASC, `poll_board_BOARDID` ASC),
  CONSTRAINT `fk_mypoll_poll1`
    FOREIGN KEY (`poll_POLLID` , `poll_board_BOARDID`)
    REFERENCES `test`.`poll` (`POLLID` , `board_BOARDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


-- -----------------------------------------------------
-- Table `test`.`userinf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`userinf` ;

CREATE TABLE IF NOT EXISTS `test`.`userinf` (
  `USERID` VARCHAR(20) NOT NULL,
  `USERNAME` VARCHAR(60) NOT NULL,
  `USERPW` VARCHAR(20) NOT NULL,
  `NICKNAME` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(60) NULL DEFAULT NULL,
  `PHNNUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(60) NULL DEFAULT NULL,
  `CREATEDATE` DATETIME NOT NULL,
  `UPDATEDATE` DATETIME NULL DEFAULT NULL,
  `mypoll_POLLID` INT(11) NOT NULL,
  `mypoll_USERID` VARCHAR(20) NOT NULL,
  `mypoll_poll_POLLID` INT(11) NOT NULL,
  `mypoll_poll_board_BOARDID` INT(11) NOT NULL,
  PRIMARY KEY (`USERID`, `mypoll_POLLID`, `mypoll_USERID`, `mypoll_poll_POLLID`, `mypoll_poll_board_BOARDID`),
  INDEX `fk_userinf_mypoll1_idx` (`mypoll_POLLID` ASC, `mypoll_USERID` ASC, `mypoll_poll_POLLID` ASC, `mypoll_poll_board_BOARDID` ASC),
  CONSTRAINT `fk_userinf_mypoll1`
    FOREIGN KEY (`mypoll_POLLID` , `mypoll_USERID` , `mypoll_poll_POLLID` , `mypoll_poll_board_BOARDID`)
    REFERENCES `test`.`mypoll` (`POLLID` , `USERID` , `poll_POLLID` , `poll_board_BOARDID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
